### ISSUE TITLE
App crashes when opening

### ISSUE THREAD

**Issue by Thewisem** [stingle/stingle-photos-android#93]
Here's a log
FATAL EXCEPTION: main
Process: org.stingle.photos, PID: 19844
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/android-arm/libjnidispatch.so) not found in resource path (.)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1033)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:989)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.sun.jna.Native.register(Native.java:1723)
	at com.goterl.lazycode.lazysodium.SodiumAndroid.<init>(SodiumAndroid.java:36)
	at com.goterl.lazycode.lazysodium.SodiumAndroid.<init>(SodiumAndroid.java:17)
	at org.stingle.photos.Crypto.Crypto.<init>(Crypto.java:92)
	at org.stingle.photos.StinglePhotosApplication.onCreate(StinglePhotosApplication.java:61)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6017)
	at android.app.ActivityThread.-wrap3(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1727)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by Thewisem** [comment]
Then the crash notification keeps on coming. I had to force stop the app

**Comment by alexamiryan** [comment]
Something is definitely wrong with your android device. libjnidispatch.so which is not found is a system file and is not a part of Stingle Photos.
